sectorNames=[
 'Crop and animal production, hunting and related service activities',
 'Forestry and logging',
 'Fishing and aquaculture',
 'Mining and quarrying',
 'Manufacture of food products; beverages and tobacco products',
 'Manufacture of textiles, wearing apparel, leather and related products',
 'Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials',
 'Manufacture of paper and paper products',
 'Printing and reproduction of recorded media',
 'Manufacture of coke and refined petroleum products',
 'Manufacture of chemicals and chemical products',
 'Manufacture of basic pharmaceutical products and pharmaceutical preparations',
 'Manufacture of rubber and plastic products',
 'Manufacture of other non-metallic mineral products',
 'Manufacture of basic metals',
 'Manufacture of fabricated metal products, except machinery and equipment',
 'Manufacture of computer, electronic and optical products',
 'Manufacture of electrical equipment',
 'Manufacture of machinery and equipment n.e.c.',
 'Manufacture of motor vehicles, trailers and semi-trailers',
 'Manufacture of other transport equipment',
 'Manufacture of furniture; other manufacturing',
 'Repair and installation of machinery and equipment',
 'Electricity, gas, steam and air conditioning supply',
 'Water collection, treatment and supply',
 'Sewerage, waste management, remediation activities',
 'Construction',
 'Wholesale and retail trade and repair of motor vehicles and motorcycles',
 'Wholesale trade, except of motor vehicles and motorcycles',
 'Retail trade, except of motor vehicles and motorcycles',
 'Land transport and transport via pipelines',
 'Water transport',
 'Air transport',
 'Warehousing and support activities for transportation',
 'Postal and courier activities',
 'Accommodation and food service activities',
 'Publishing activities',
 'Motion picture, video, television programme production; programming and broadcasting activities',
 'Telecommunications',
 'Computer programming, consultancy, and information service activities',
 'Financial service activities, except insurance and pension funding',
 'Insurance, reinsurance and pension funding, except compulsory social security',
 'Activities auxiliary to financial services and insurance activities',
 'Imputed rents of owner-occupied dwellings',
 'Real estate activities',
 'Legal and accounting activities; activities of head offices; management consultancy activities',
 'Architectural and engineering activities; technical testing and analysis',
 'Scientific research and development',
 'Advertising and market research',
 'Other professional, scientific and technical activities; veterinary activities',
 'Rental and leasing activities',
 'Employment activities',
 'Travel agency, tour operator and other reservation service and related activities',
 'Security and investigation, service and landscape, office administrative and support activities',
 'Public administration and defence; compulsory social security',
 'Education',
 'Human health activities',
 'Residential care activities and social work activities without accommodation',
 'Creative, arts and entertainment activities; libraries, archives, museums and other cultural activities; gambling and betting activities',
 'Sports activities and amusement and recreation activities',
 'Activities of membership organisations',
 'Repair of computers and personal and household goods',
 'Other personal service activities',
 'Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use',
 'Activities of extraterritorial organisations and bodies']

GrossCapitalFormation=[
7444.62,
 456.39,
 56.16,
 1268.44,
 0.55,
 1603.87,
 9296.21,
 0.52,
 5.73,
 0.0,
 40.98,
 0.36,
 3960.68,
 7048.47,
 3327.25,
 70248.18,
 99794.45,
 48148.64,
 237529.45,
 166506.4,
 101785.37,
 47797.81,
 86048.8,
 263.9,
 10.92,
 55.88,
 1310617.3,
 32635.51,
 106583.15,
 32345.85,
 19378.02,
 1652.6,
 1640.49,
 514.58,
 0.0,
 418.81,
 42452.65,
 14855.89,
 0.0,
 295165.6,
 57.03,
 2611.9,
 1166.4,
 0.0,
 38782.86,
 39242.12,
 92446.33,
 368159.24,
 6.95,
 84.08,
 2569.35,
 148.03,
 171.3,
 11822.25,
 4105.41,
 153.41,
 8.2,
 9.13,
 4323.31,
 9.3,
 8.44,
 3397.31,
 7.41,
 0.07,
 8.38]
