import commonVar as cmv

def initSeries():
    
    cmv.totalProductionSeries=[]
    cmv.totalProductionInfraVarSeries=[]
    cmv.totalProfitSeries=[]
    cmv.totalProfitInfraVarSeries=[]
    cmv.totalInitialInventoriesSeries=[]
    cmv.totalInitialInventoriesInfraVarSeries=[]
    cmv.totalFinalInventoriesSeries=[]
    cmv.totalFinalInventoriesInfraVarSeries=[]
    cmv.totalConsumptionSeries=[]
    cmv.totalEntrepreneurConsumptionSeries=[]
    cmv.totalNonEntrepreneurConsumptionSeries=[]
    cmv.totalConsumptionInfraVarSeries=[]
    cmv.totalInvestmentSeries=[]
    cmv.totalInvestmentInfraVarSeries=[]
    cmv.totalCashMoneySeries=[]
    cmv.totalCashMoneyInfraVarSeries=[]
    cmv.totalCheckingAccountSeries=[]
    cmv.totalCheckingAccountInfraVarSeries=[]
    cmv.totalBankAccountSeries=[]
    cmv.totalBankAccountInfraVarSeries=[]
    cmv.totalAddedValueSeries=[]
    cmv.totalAddedValueInfraVarSeries=[]
    cmv.privateClientsTotalInterestOnDepositsSeries=[]
    cmv.privateClientsTotalInterestOnLoansSeries=[]
    cmv.commercialClientsTotalInterestOnDepositsSeries=[]
    cmv.commercialClientsTotalInterestOnLoansSeries=[]
    cmv.privateClientsTotalInterestOnDepositsInfraVarSeries=[]
    cmv.privateClientsTotalInterestOnLoansInfraVarSeries=[]
    cmv.commercialClientsTotalInterestOnDepositsInfraVarSeries=[]
    cmv.commercialClientsTotalInterestOnLoansInfraVarSeries=[]
    cmv.totalDebtsVsAgentsSeries=[]
    cmv.totalCreditsVsAgentsSeries=[]
    cmv.totalDebtsVsFirmsSeries=[]
    cmv.totalCreditsVsFirmsSeries=[]
    cmv.totalDebtsVsAgentsInfraVarSeries=[]
    cmv.totalCreditsVsAgentsInfraVarSeries=[]
    cmv.totalDebtsVsFirmsInfraVarSeries=[]
    cmv.totalCreditsVsFirmsInfraVarSeries=[]

    cmv.totalLostProductionSeries=[]